### ISSUE TITLE
Broken Register application links in wiki

### ISSUE THREAD

**Issue by bawn92** [Etalio/mdi-android-sdk#12]
Could you please update the links in the wiki to the webpage where I can register my app in order to obtain:

Client id
Client secret
Redirect url

**Comment by stoyicker** [comment]
What do you mean by the wiki?

**Comment by bawn92** [comment]
I meant the readme.md

**Comment by stoyicker** [comment]
Should be good to go now, thanks for the report. Bear in mind that we are undergoing instability issues in our backend so you might experience errors on some of the links, but I can assure you that they are the correct ones, just wait and try again later.
Also, if you plan to start developing your app now, you will need to obtain the module by either cloning the repository or downloading it, as we are still finalizing the maven deployment and therefore it is not available as a binary release just yet - but check back soon!
